#!/usr/bin/env bash
###
# Project: DEV4PHP
# Author: Walker de Alencar (@walkeralencar)
###

VERSION=`cat /vagrant/VERSION` ## Version project
HOSTNAME=php.dev               ## Define hostname for server, need to change in './Vagrantfile' too
SWAPSIZE=1024M                 ## Define swap file size. default: 1024M
