#!/usr/bin/env bash
###
# @package  DEV4PHP
# @author   Walker de Alencar <@walkeralencar>
##

## Perform an unattended installation
export DEBIAN_FRONTEND=noninteractive

## Configurations
VERSION=`cat /vagrant/VERSION` ## Version project
HOSTNAME=php.dev               ## Define hostname for server, need to change in './Vagrantfile' too
SWAPSIZE=1024M                 ## Define swap file size. default: 1024M